version: "2"

services:
  scheduler:
    build: .
    image: magsol/distributed-dask:latest
    ports:
      - "8786:8786"
      - "8787:8787"
    command: start-scheduler.sh
    container_name: dist-scheduler

  worker:
    build: .
    image: magsol/distributed-dask:latest
    command: start-worker.sh
    depends_on:
      - scheduler
